parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: 
    database_user: 
    database_password: 
    host : 
    locale: en
    secret: 
    database_path: null

    per_item_page: 10
    upload : "/uploads/"
    upload_accept_file_types : "/(gif|jpg|png|jpeg|svg)$/i"
    dir_rss_feed : "/uploads/rss-feed"
    time_cron : 30
    rss_user : ''
    rss_password: ''

